// Generated by https://pagedraw.io/pages/11669
import React from 'react';
import Button from './button';
import './artboard.css';


function render() {
    return <div className="artboard-artboard-0">
        <div className="artboard-0" /> 
        <div className="artboard-1">
            <div className="artboard-1-0" /> 
            <div className="artboard-rectangle-0">
                <div className="artboard-1-1-0">
                    <img src="https://ucarecdn.com/debe0eb7-0f38-4829-ab3f-e09976a4725b/" className="artboard-image-0" /> 
                </div>
                <div className="artboard-1-1-1">
                    <div className="artboard-1-1-1-0">
                        <div className="artboard-1-1-1-0-0">
                            <div className="artboard-1-1-1-0-0-0">
                                <div className="artboard-rectangle_2">
                                    <div className="artboard-1-1-1-0-0-0-0-0">
                                        <div className="artboard-cliquetrip_helps_you_plan_your_dream_vacation_or_dream_conference_when_your_group_has_to_decide_on_locations_and_dates_-0">
                                            {"CliqueTrip helps you plan your dream vacation (or dream conference) when your group has to decide on locations and dates."}
                                        </div>
                                    </div>
                                </div>
                                <div className="artboard-image-1">
                                    <div className="artboard-1-1-1-0-0-0-1-0">
                                        <div className="artboard-button-2"><Button /> </div>
                                    </div>
                                </div>
                                <img src="https://ucarecdn.com/cbd2c698-3f50-48a9-a2e1-19bab6f54d9c/" className="artboard-image_2" /> 
                            </div>
                        </div>
                    </div>
                </div>
                <div className="artboard-1-1-2" /> 
            </div>
            <div className="artboard-1-2" /> 
        </div>
        <div className="artboard-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
