// Generated by https://pagedraw.io/pages/11460
import React from 'react';
import './button.css';


function render() {
    return <div className="button-button-1">
        <div className="button-0">
            <div className="button-path-3">
                <div className="button-0-0-0">
                    <div className="button-hello_world-1">Hello world</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
