// Generated by https://pagedraw.io/pages/11669
import React from 'react';
import './button.css';


function render() {
    return <div className="button-button-0">
        <div className="button-0">
            <div className="button-rectangle_2">
                <div className="button-0-0-0">
                    <div className="button-next_-7">Next</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
